# print("Test")
# print("Test")
# print("Please enter your full name, house / flat number and street number or name:")
# fname=input("first name: ")
# lname=input("last name: ")
# fullname=fname+" "+lname
# length=len(fullname.strip())
# house=input("house / flat number: ")
# street=input("street number and name: ")
# print("From: ", fullname, "\n Address: ",house, street)
# print("The length of your name is ",length)
# print("Please enter a noun and a letter: ")
# string1=input("Noun: ")
# letter=input("Letter: ")
# string2= string1.replace(letter, "@")
# # print(string2)

testString="This is a test string"
textFind=input("Enter a word to find: ")
print(testString.find(textFind))